function [TimeStamp, x, y, theta] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [VARNAME8,VARNAME21,VARNAME23,VARNAME25] = IMPORTFILE(FILENAME) Reads
%   data from text file FILENAME for the default selection.
%
%   [VARNAME8,VARNAME21,VARNAME23,VARNAME25] = IMPORTFILE(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [VarName8,VarName21,VarName23,VarName25] =
%   importfile('02-calibration-test--f-12p.log',1, 8850);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/01/08 13:04:30

%% Initialize variables.
delimiter = {'\t',',',' ','','[',']'};
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column8: double (%f)
%	column21: double (%f)
%   column23: double (%f)
%	column25: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%*s%*s%*s%*s%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%*s%f%*s%f%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName8 = dataArray{:, 1};
VarName21 = dataArray{:, 2};
VarName23 = dataArray{:, 3};
VarName25 = dataArray{:, 4};


TimeStamp = VarName8;
x = VarName21;
y = VarName23;
theta = VarName25;

