/**
 * @file rollo.hpp
 * @author Rabbia Asghar
 * @author Ernest Skrzypczyk
 * 
 * @date 20/2/16
 * 
 * @brief Header file holding Rollo specific parameters and global references for the ROS nodes
 *
 */


//! ## Rollo

//! Axle length
#define ROLLO_AXLE_L 0.0205
//! Wheel radius:
//! - Left
#define ROLLO_WHEEL_RADIUS_L 0.0076
//! - Right
#define ROLLO_WHEEL_RADIUS_R 0.0076
// Original values
// //! - Left
// #define ROLLO_WHEEL_RADIUS_L 0.020
// //! - Right
// #define ROLLO_WHEEL_RADIUS_R 0.020
//! Number of wheels
#define ROLLO_WHEEL_N 4
//! Maximum speed [%]
#define ROLLO_SPEED_MAX 56
//! Minimum speed [%]
#define ROLLO_SPEED_MIN 6

//! Mathematical constants

//! Pi
#define PI 3.1415926535

//! Node names

//! Communication
#define CM "COMM"
//! Control
#define CT "CTRL"
//! Localization
#define LC "LOC "
//! Odometry
#define OD "ODOM"
//! Preprocessor
#define PP "PREP"
//! Extended Kalman filter
#define KF "EKF "
//! Visualization
#define VS "VIS "


//! ROS

//! ROS package name
#define PACKAGE "Rollo"

//! ROS topics
// Alternative destinations for topics, divided by node names
// #define TOPIC_COMM_WS "/Rollo/communication/wheelspeed"
// #define TOPIC_CTRL_CMD_VEL "/Rollo/control/cmd_vel"
// #define TOPIC_EKF "/Rollo/ekf/ekf"
// #define TOPIC_PREP_MC "/Optitrack_Rollo/ground_pose"
// #define TOPIC_PREP_P2DT "/Rollo/preprocessor/pose2dstamped"

//! Topic for wheel speed containing the actual speed of wheel, preferably extracted from encoders or if not available by using a lookup table
#define TOPIC_COMM_WS "/Rollo/wheelspeed"
//! Topic for commands generated by control node expressed in linear and angular velocity
#define TOPIC_CTRL_CMD_VEL "/Rollo/cmd_vel"
//! Topic for extended Kalman filter results with all three estimated states and covariance matrix, stamped
#define TOPIC_EKF "/Rollo/ekf"
//! Topic for motion capture data
#define TOPIC_PREP_MC "/Optitrack_Rollo/ground_pose"
//! Topic for position and orientation, stamped
#define TOPIC_PREP_P2DT "/Rollo/pose2dstamped"

//! GNU/Linux terminal color codes

//! Reset
#define CR "\033[0m"

//! Color 1
#define C1 "\033[38;5;63m"
//! Color 2
#define C2 "\033[38;5;220m"
//! Color 3
#define C3 "\033[38;5;87m"
//! Color 4
#define C4 "\033[38;5;84m"
//! Color 5
#define C5 "\033[38;5;160m"
//! Color 6
#define C6 "\033[38;5;161m"
//! Color 7
#define C7 "\033[38;5;162m"
//! Color 8
#define C8 "\033[38;5;22m"

//! Error
#define CEE "\033[38;5;124m" /* Error */
//! Success
#define CSS "\033[38;5;154m" /* Success */
//! Warning
#define CWW "\033[38;5;202m" /* Warning */
